### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by anmolgaur45** [Jimoh1993/JPMorgan-Chase-Software-Engineering-Virtual-Experience#1]
Do you have the patch file for the task 3?

**Comment by Jimoh1993** [comment]
I uploaded the patch file for the task 3 during the Virtual Experience. Probably it got deleted when my GitHub account complains of vulnerable files. Now my second laptop is not with me currently. Now we are in lockdown and curfew no movement because of COVID-19.
